### ISSUE TITLE
Hi!

### ISSUE THREAD

**Issue by zdanl** [JairusSW/as-fetch#2]
Hi. asc installed, all as you said, but as-fetch not found. 

Is there a special .asc_modules or so, or are you just still working?

**Comment by JairusSW** [comment]
I'm still working on it. Will release a updated version in less than a week :)

**Comment by JairusSW** [comment]
The version on NPM is for AssemblyScript 0.19.x
You can use it on 0.27.x, but you need to use `import { fetch } from "as-fetch/assembly";`. You also need to use the loader.

But, I'll be updating it, so its probably best to wait

**Comment by JairusSW** [comment]
I have a mvp going now. Check out the repo's readme
