### ISSUE TITLE
Unable to use it in subgraphs

### ISSUE THREAD

**Issue by nareshkatta99** [JairusSW/as-fetch#3]
Subgraph is a web3 service that indexes blockchain events.

Sometimes data needs to be retrieved from some centralized servers.

We tried using this library for same but not able to use.

Could you help us with this @JairusSW .

**Comment by JairusSW** [comment]
Hello there!
Can you tell me what version of AssemblyScript you are using now?

The version of as-fetch that is on NPM is built for `0.19.x`, but I am refactoring it to work for `0.27.x`. If you are on `0.19.x` and you want to use it, try importing like shown in issue #2 .

I should release a updated version soon, but I am busy at the moment.

**Comment by MaxGraey** [comment]
blockchains usually disallow any unpredictable & external behavior. Also as-fetch depends on JavaScript runtime while The Graph has own runtime. So I don't think that as-fetch or something similar can be used in your case

**Comment by JairusSW** [comment]
Yes, that should be the issue. Closing now
